name: line message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send message
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            Triggered ${{github.repository}}'s ${{ github.event_name }} event.
            show the github varable ref: ${{ github.ref }}
            show the github varable commit: ${{ github.sha }}
            Commit: ${{ github.event.head_commit.message }}

      - name: send sticker message
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            The ${{ github.event_name }} event triggered final step.
            echo This event is a pull request that had an assignee removed.
          sticker_id: 1
          package_id: 1
      - name: send image url message
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            ${{github.repository}} send image test.
          image_url: 'https://raw.githubusercontent.com/louis70109/line-notify-action/master/tests/image1.png'
      - name: send image file message
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            ${{github.repository}} send image file.
          image_file: './tests/chatbot.png'
