name: line message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send message
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            Triggered ${{github.repository}}'s ${{ github.event_name }} event.
            show the github varable ref: ${{ github.ref }}
            show the github varable commit: ${{ github.sha }}
            Commit Message: ${{ github.event.head_commit.message }}

      - name: send custom message
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            The ${{ github.event_name }} event triggered final step.
            echo This event is a pull request that had an assignee removed.
