name: line message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: The ${{ github.event_name }} event triggered first step.

      - name: send message useing with
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            The ${{ github.event_name }} event triggered second step.
            show the github varable ref: ${{ github.ref }}
            show the github varable commit: ${{ github.sha }}
            show the github varable ref: {{ commit.ref }}
            show the github varable commit: {{ commit.sha }}
            Commit Message: ${{ github.event.head_commit.message }}

      - name: send custom message
        uses: ./
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            The ${{ github.event_name }} event triggered final step.
            echo This event is a pull request that had an assignee removed.
